sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_voltage
    name: "battery_rated_voltage"
    entity_category: diagnostic
    address: 0x3004
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    skip_updates: 10
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_current
    name: "battery_rated_current"
    entity_category: diagnostic
    address: 0x3005
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    skip_updates: 10
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_rated_power
    name: "battery_rated_power"
    entity_category: diagnostic
    address: 0x3006
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD_R
    skip_updates: 10
    accuracy_decimals: 1
    filters:
      - multiply: 0.01


  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_voltage
    name: "Charging voltage"
    address: 0x3104
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_current
    name: "Charging current"
    address: 0x3105
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_power
    name: "Charging power"
    address: 0x3106
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    device_class: "power"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_temperature
    name: "Battery temperature"
    address: 0x3110
    unit_of_measurement: °C
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_volt_settings
    name: "Remote real voltage"
    address: 0x311D
    unit_of_measurement: "°C"
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

select:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_mode
    name: "Charging controller type"
    address: 0x3008
    value_type: U_WORD
    optionsmap:
      "Connect/disconnect": 0
      "PWM": 1
      "MPPT": 2
