
sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_voltage
    name: "array_rated_voltage"
    address: 0x3000
    skip_updates: 60
    unit_of_measurement: "V"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    lambda: |-
      int i;
      float sumpre, avgpre = 0.0;
      float sumpost, avgpost = 0.0;
      auto pv = id(pv_history);

      // calc average before
      for (i = 0; i < 7; i++)
        sumpre += pv[i];
      avgpre = sumpre / 8.0;

      // insert new measurement
      for (i = 1; i < 7; i++)
        pv[i] = pv[i-1];
      pv[7] = x;

      // calc average after
      for (i = 0; i < 7; i++)
        sumpost += pv[i];
      avgpost = sumpost / 8.0;

      // publish changes to template sensor
      if ((avgpre < 5.0) && (avgpost >= 5.0))
        id(day_night_mode).publish_state("day");

      if ((avgpre >= 5.0) && (avgpost < 5.0))
        id(day_night_mode).publish_state("night");

      return x;
    filters:
        - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_current
    name: "array_rated_current"
    address: 0x3001
    unit_of_measurement: "A"
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
        - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: array_rated_power
    name: "array_rated_power"
    address: 0x3002
    register_count: 2
    unit_of_measurement: "W"
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_input_voltage
    name: "PV array input voltage"
    address: 0x3100
    unit_of_measurement: "V" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_input_current
    name: "PV array input current"
    address: 0x3101
    unit_of_measurement: "A" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: pv_input_power
    name: "PV array input power"
    address: 0x3102
    unit_of_measurement: "W" ## for any other unit the value is returned in minutes
    register_type: read
    value_type: U_DWORD_R
    accuracy_decimals: 1
    device_class: "power"
    filters:
      - multiply: 0.01
