sensor:
  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_type
    address: 0x9000
    name: "Battery Type"
    entity_category: diagnostic
    register_type: holding
    value_type: U_WORD
    skip_updates: 10

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_capacity
    address: 0x9001
    name: "Battery Capacity"
    entity_category: diagnostic
    register_type: holding
    value_type: U_WORD
    skip_updates: 10

  - platform: modbus_controller
    modbus_controller_id: epever
    id: temperature_compensation_coefficient
    address: 0x9002
    name: "Temperature compensation coefficient"
    entity_category: diagnostic
    unit_of_measurement: "mV/°C/2V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: high_voltage_disconnect
    address: 0x9003
    name: "High Voltage disconnect"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: charging_limit_voltage
    address: 0x9004
    name: "Charging limit voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

    force_new_range: true

  - platform: modbus_controller
    modbus_controller_id: epever
    id: over_voltage_reconnect
    address: 0x9005
    name: "Over voltage reconnect"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: equalization_voltage
    address: 0x9006
    name: "Equalization voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: boost_voltage
    address: 0x9007
    name: "Boost voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: float_voltage
    address: 0x9008
    name: "Float voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

    force_new_range: true

  - platform: modbus_controller
    modbus_controller_id: epever
    id: boost_reconnect_voltage
    address: 0x9009
    name: "Boost reconnect voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: low_voltage_reconnect
    address: 0x900A
    name: "Low voltage reconnect"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: under_voltage_recover
    address: 0x900B
    name: "Under voltage recover"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: under_voltage_warning
    address: 0x900C
    name: "Under voltage warning"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

    force_new_range: true

  - platform: modbus_controller
    modbus_controller_id: epever
    id: low_voltage_disconnect
    address: 0x900D
    name: "Low voltage disconnect"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: discharging_limit_voltage
    address: 0x900E
    name: "Discharging limit voltage"
    entity_category: diagnostic
    unit_of_measurement: "V"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_temperature_warning_upper_limit
    address: 0x9017
    name: "Battery temperature warning upper limit"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: battery_temperature_warning_lower_limit
    address: 0x9018
    name: "Battery temperature warning lower limit"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: controller_inner_temperature_upper_limit
    address: 0x9019
    name: "Controller inner temperature upper limit"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: controller_inner_temperature_upper_limit_recover
    address: 0x901A
    name: "Controller inner temperature upper limit recover"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: power_component_temperature_upper_limit
    address: 0x901B
    name: "Power component temperature upper limit"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

    force_new_range: true

  - platform: modbus_controller
    modbus_controller_id: epever
    id: power_component_temperature_upper_limit_recover
    address: 0x901C
    name: "Power component temperature upper limit recover"
    entity_category: diagnostic
    unit_of_measurement: "°C"
    register_type: holding
    value_type: S_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: epever
    id: line_impedance
    address: 0x901D
    name: "Line Impedance"
    entity_category: diagnostic
    unit_of_measurement: "mOhm"
    register_type: holding
    value_type: U_WORD
    skip_updates: 10
    filters:
      - multiply: 0.01

